title: "Jekyll-Theme-MDUI"
description: "A Jekyll theme based on MDUI"
url: 
baseurl: 
author: "KeJun"
avatar: "https://ooo.0o0.ooo/2017/05/26/5928368d409dd.png"
lang: "zh-CN"
paginate: 5
paginate_path: "/blog/page:num/"

disqus_shortname: "kejun"
disqus_proxy: false
disqus_proxy_url: "http://disqus.kejun.space"
disqus_api_key: "a5jdpCqGkFzT4bFTKwrkTNqSUfTrz9pnxHOb9ZUro32WYpgAf2MnlLyikTGkKmiQ"

google_analytics: ""
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor